//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.29 at 11:44:03 PM CEST 
//


package modelFromXsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the modelFromXsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: modelFromXsd
     * 
     */
    public ObjectFactory() {
    }
    
    public IzvodStanja createIzvodStanja(){
    	return new IzvodStanja();
    }
    
    public StavkaIzvoda createStavkaIzvoda(){
    	return new StavkaIzvoda();
    }
    
    public NalogZaPlacanje createNalogZaPlacanje(){
    	return new NalogZaPlacanje();
    }
    
    public MT103 createMT103(){
    	return new MT103();
    }
    /**
     * Create an instance of {@link MT102 }
     * 
     */
    public MT102 createMT102() {
        return new MT102();
    }

    /**
     * Create an instance of {@link ZaglavljeMT102 }
     * 
     */
    public ZaglavljeMT102 createZaglavljeMT102() {
        return new ZaglavljeMT102();
    }

    /**
     * Create an instance of {@link StavkaKliringa }
     * 
     */
    public StavkaKliringa createStavkaKliringa() {
        return new StavkaKliringa();
    }

}
